name: prestacarro_front
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # sdk
  flutter:
    sdk: flutter
  # dependencies
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  http: ^0.13.4
  rflutter_alert: ^2.0.4
  provider: ^6.0.1
  oktoast: ^3.1.0
  window_manager: ^0.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # resources
  assets:
    - assets/images/
    - assets/svgs/
  
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Italic.ttf
          style: italic